name: 🐛 Bug Report
description: Report a bug or issue with the Git Worktrees Tutorial
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: dropdown
    id: tutorial_section
    attributes:
      label: Tutorial Section
      description: Which part of the tutorial is affected?
      options:
        - Main README
        - Exercise 1 - Basic Operations
        - Exercise 2 - Parallel Features
        - Exercise 3 - Hotfix Workflow
        - Exercise 4 - AI Agents
        - Exercise 5 - Cleanup
        - Scripts (setup, cleanup, status, validation)
        - Documentation (cheatsheet, best practices, AI guide)
        - Sample Project
        - Other
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: error_output
    attributes:
      label: Error Output
      description: If applicable, paste any error messages or output
      placeholder: Paste error messages here...
      render: shell

  - type: input
    id: git_version
    attributes:
      label: Git Version
      description: What version of Git are you using?
      placeholder: "git --version"
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "macOS 13.0, Ubuntu 22.04, Windows 11, etc."
    validations:
      required: true

  - type: dropdown
    id: terminal
    attributes:
      label: Terminal/Shell
      description: What terminal or shell are you using?
      options:
        - bash
        - zsh
        - fish
        - PowerShell
        - Command Prompt
        - Git Bash
        - Other

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, workaround attempts, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this with the latest version of the tutorial
          required: true